require 'invocation/controls/no_parameters'
require 'invocation/controls/positional_parameters'
require 'invocation/controls/named_parameters'
require 'invocation/controls/block_parameter'
require 'invocation/controls/splat_parameter'
require 'invocation/controls/double_splat_parameter'
require 'invocation/controls/mixed_parameters'
